# 1. Install dependencies only when needed
FROM node:16-alpine AS deps

RUN apk add --no-cache libc6-compat

WORKDIR /app

RUN yarn global add pnpm 

COPY ./package.json ./pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

# 2. Build image, build all soruce code
FROM node:16-alpine AS builder

ENV NEXT_TELEMETRY_DISABLED=1


WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN yarn build

# 3. Production image, copy all the files and run next
FROM node:16-alpine AS runner

ENV NEXT_TELEMETRY_DISABLED=1


WORKDIR /app

ENV NODE_ENV=production

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

COPY --from=builder /app/src/public ./public

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 4009

ENV PORT 4009


CMD ["node", "server.js"]
