export const ALLOWED_DOMAINS = [
  '@kering.com',
  '@aldenteparis.com',
  '@enverselabs.com',
  '@heretique.fr',
  'pm.marteau@gmail.com',
  'chrislhamelin@gmail.com',
  '@kering.com',
  '@boucheron.com',
  '@gucci.com',
  '@ysl.com',
  '@pomellato.com',
  '@dodo.it',
  '@qeelin.com',
  '@balenciaga.com',
  '@brioni.com',
  '@alexandermcqueen.com',
];
