version: '3.7'
services:
  kering-imagination-odyssey:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: registry.gitlab.com/enverse-labs/digital-odyssey:production
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    environment:
      VIRTUAL_HOST: kering-learning-odyssey.com
      VIRTUAL_PORT: 4111
      LETSENCRYPT_HOST: kering-learning-odyssey.com

      PORT: 4111
    ports:
      - '4111:4111'
    container_name: kering-imagination-odyssey
    networks:
      - nginx_proxy_network

networks:
  nginx_proxy_network:
    external: true
