version: '3.7'
services:
  digital-odyssey-production:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: registry.gitlab.com/enverse-labs/digital-odyssey:production
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    environment:
      VIRTUAL_HOST: digital-odysser.enverselabs.com
      VIRTUAL_PORT: 4112
      LETSENCRYPT_HOST: digital-odysser.enverselabs.com
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      PORT: 4112
    ports:
      - '4112:4112'
    container_name: digital-odyssey-production
    networks:
      - nginx_proxy_network

networks:
  nginx_proxy_network:
    external: true
