version: '3.7'
services:
  digital-odyssey-staging:
    build:
      context: ../../
      dockerfile: docker/staging/Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
    image: registry.gitlab.com/enverse-labs/digital-odyssey:staging
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    environment:
      VIRTUAL_HOST: digital-odyssey-staging.enverselabs.com
      VIRTUAL_PORT: 4111
      LETSENCRYPT_HOST: digital-odyssey-staging.enverselabs.com

      PORT: 4111
    ports:
      - '4111:4111'
    container_name: digital-odyssey-staging
    networks:
      - nginx_proxy_network

networks:
  nginx_proxy_network:
    external: true
